= Create a Producer Connector

This guide explains how to create a producer connector using the Connector SDK.
Therefore, we will create a simple connector that generates a message at regular intervals.

== The Date Time Producer Connector

The Date Time Producer Connector is a simple connector that generates a message containing the current date and time.
It has only a single configuration option: the interval in seconds at which the connector should generate a new message.

.The Date Time Producer Connector Configuration
[cols="2,3,2,1",options="header"]
|===
| Configuration Key
| Description
| Default Value
| Required

| interval
| The interval in seconds at which the connector should generate a new message.
| 60
| Yes
|===

Everytime the interval is reached a new message is generated and sent to the TRANSCONNECT.
The message is a simple XML document containing the current date and time.

.An example message generated by the Date Time Producer Connector
[source,xml]
....
<ROOT>
    <DATETIME>2021-01-01T12:00:00</DATETIME>
</ROOT>
....

Now that we have a basic understanding of the connector, let's start with the project creation.

include::partial$download-sample.adoc[]