services:
  kroki:
    image: yuzutech/kroki:0.26.0
    depends_on:
      - mermaid
      - bpmn
      - excalidraw
    environment:
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
    ports:
      - "8000:8000"
  mermaid:
    image: yuzutech/kroki-mermaid:0.26.0
    expose:
      - "8002"
  bpmn:
    image: yuzutech/kroki-bpmn:0.26.0
    expose:
      - "8003"
  excalidraw:
    image: yuzutech/kroki-excalidraw:0.26.0
    expose:
      - "8004"
